---
- hosts: test_servers
  tasks:
    - name: Create directory
      file:
        path: $HOME/tmp
        state: directory
        owner: ansible
        mode: 0755

    - name: copy file
      copy:
        src: $HOME/ansible.cfg
        dest: $HOME/tmp/
        owner: ansible
        mode: 0644