---
galaxy_info:
  author: "Ansible User"
  company: Example.com
  license: GNU General Public License
  min_ansible_version: 2.0
  platform:
    - name: Ubunto
      versions:
       - precise
       - quantal
       - raring
       - saucy

dependencies:
  - { role: common, os_parameter: 3 }
  - { role: nginx, when: "server_groups == 'web_servers'" }