---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false
  vars:
    tagging: untagged
    vlan_id: 329
    interface_info: 
      - { assign_interface: 1.1, vlan_name: 'internal' }
      - { assign_interface: 1.2, vlan_name: 'external' }
      - { assign_interface: 1.3, vlan_name: 'HA' }

  tasks:
    - name: create internal vlan
      f5networks.f5_modules.bigip_vlan:
        interfaces:
          - interface: "{{ item.assign_interface }}"
            tagging: "{{ tagging }}"
        name: "{{ vlan_name }}"
        tag: "{{ item.vlan_id }}"
        state: present
        loop: "{{ interface_info }}"
