---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false
  vars:
    off_member:
      - { name: "web_node001", addr: 10.44.228.161 }
      - { name: "web_node002", addr: 10.44.228.162 }
      - { name: "web_node003", addr: 10.44.228.163 }

  tasks:
    - name: offline pool member
      f5networks.f5_modules.bigip_pool_member:
        state: forced_offline
        pool: http_pool
        aggregate:
          - name: "{{ off_member[2].name }}"
            address: "{{ off_member[2].addr }}"
            port: 80
