---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false

  tasks:
    - name: create standard virtual server
      f5networks.f5_modules.bigip_virtual_server:
        state: present
        name: web_server
        source: '0.0.0.0/0'
        destination: '192.168.1.80'
        port: '8080'
        profiles:
          - http_profile
        enabled_vlans:
          - /Common/external
        snat: automap
        type: standard
        pool: http_pool
