---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false
  vars:
    tagging: untagged
    interface_info: 
      - { assign_interface: 1.1, vlan_name: 'internal', vlan_id: 328 }
      - { assign_interface: 1.2, vlan_name: 'external', vlan_id: 2500 }
      - { assign_interface: 1.3, vlan_name: 'HA', vlan_id: 329 }

  tasks:
    - name: create vlan
      f5networks.f5_modules.bigip_vlan:
        interfaces:
          - interface: "{{ item.assign_interface }}"
            tagging: "{{ tagging }}"
        name: "{{ item.vlan_name }}"
        tag: "{{ item.vlan_id }}"
        state: present
      loop: "{{ interface_info }}"
