---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false
  vars:
    pool_name: http_pool
    nodes:
      - { name: "web_node001", addr: 10.44.228.161 }
      - { name: "web_node002", addr: 10.44.228.162 }
      - { name: "web_node003", addr: 10.44.228.163 }

  tasks:
    - name: create pool
      f5networks.f5_modules.bigip_pool:
        state: present
        name: "{{ pool_name }}"
        monitors: http_monitor
        lb_method: least-connections-member

    - name: add a pool member
      f5networks.f5_modules.bigip_pool_member:
        state: present
        pool: "{{ pool_name }}"
        aggregate:
          - name: "{{ item.name }}"
            address: "{{ item.addr }}"
            port: 80
      loop: "{{ nodes }}"
