---
- hosts: bigip
  connection: ansible.builtin.local
  gather_facts: false
  vars:
    off_member
      - { name: web_node003, addr: 10.44.228.163 }

  tasks:
    - name: offline pool member
      f5networks.f5_modules.bigip_pool_member:
        state: forced_offline
        pool: http_pool_1
        aggregate:
          - name: "{{ off_member.name }}"
            address: "{{ off_member.addr }}"
            port: 80
