---
- name: Management Docker
  hosts: localhost
  vars:
    docker_hosts:
      - '10.44.229.71:2376'
      - '10.44.229.72:2376'
    required_docker_images: "ansible/centos7-ansible"
    tmp_dir: docker_repo
    docker_auth: 
      username: ntanizawa
      password: T4at$N~HWV
      email: n-tanizawa@netone.co.jp

  tasks:
    - name: Install git and docker ## git cloneとdocker login用
      dnf:
        name: 
          - git
          - docker
        state: present
      become: yes
      become_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python
        
    - name: Create docker local network
      docker_network:
        docker_host: "{{ item }}"
        name: ansible_network
      with_items: "{{ docker_hosts }}"

    - name: Docker login
      command: docker login -u "{{ docker_auth.username }}" -p "{{ docker_auth.password }}"
      become: yes
      become_user: root

    - name: Pull docker image
      docker_image:
        docker_host: "{{ item }}"
        name: "{{ required_docker_images }}"
        source: pull
      with_items:
        - "{{ docker_hosts }}"

    - name: Get Nginx Dockerfile
      git:
        repo: https://github.com/nginxinc/docker-nginx.git
        dest: "{{ tmp_dir }}"

    - name: Build Dockerfile
      docker_image:
        docker_host: "{{ item }}"
        build:
          path: "{{ tmp_dir }}/stable/debian"
          pull: yes
        name: nginxinc/docker-nginx
        tag: v1
        source: build
      with_items: "{{ docker_hosts }}"

    - name: Inspect docker image
      docker_image_facts:
        docker_host: "{{ item }}"
        name: nginxinc/docker-nginx
      with_items: "{{ docker_hosts }}"
      register: image_fact

    - name: Show docker image facts
      debug:
        var: image_fact.results

    - name: Run nginx docker container
      docker_container:
        docker_host: "{{ item }}"
        name: "nginx-1"
        image: "nginxinc/docker-nginx:v1"
        networks:
          - name: ansible_network
        purge_networks: yes
        ports:
          - "8080:80"
      with_items: "{{ docker_hosts }}"

    - name: Run ansible docker container
      docker_container:
        docker_host: "{{ item }}"
        name: "ansible-1"
        image: "{{ required_docker_images }}"
        command: /bin/bash
        tty: yes
        interactive: yes
      with_items: "{{ docker_hosts }}"
