---
##(1)rsyslog設定の配備
- name: configure / Setup rsyslog configuration file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644 
    backup: yes

##(2)HAProxy設定の配備
- name: configure / Setup HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644 
    backup: yes

##(3)rsyslogの再起動
- name: configure / Start rsyslog service
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

##(4)HAProxyの起動
- name: configure / Start haproxy service
  systemd:
    name: haproxy
    state: reloaded
    enabled: yes

##(5)HAProxyの起動確認
- name: configure / Wait for haproxy reload
  wait_for:
    port: "{{ haproxy_stats_port }}"
    delay: 3
    timeout: 60