---
#(1)SELinuxのモード変更
- name: configure / SELinux permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux.config_mode == 'enforcing' 

#(2)IPv6インターフェースの無効化
- name: configure / Disable ipv6 interface
  sysctl: ## sysctl.confのエントリを変更するモジュール
    state: present
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

##(3)YUMパッケージのアップデート
- name: configure / Update yum packeges
  yum:
    name: '*'
    state: latest
    update_cache: yes
  async: 1000
  poll: 1
  register: yum_sleeper
  ignore_errors: yes

##(4)EPELリポジトリの設定
- name: configure / Import EPEL Repository
  yum: 
    name: epel-release
    state: latest
    update_cache: yes
