---
##(1)PHP-FPMのdefault設定のバックアップ
- name: configure / Backup original file
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/php-fpm.default
  args:
    creates: "/etc/php-fpm.d/php-fpm.default"

##(2)PHP-FPM設定の配備
- name: configure / Configuration file
  template:
    src: wordpress.conf.j2
    dest: /etc/php-fpm.d/wordpress.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

##(3)PHP-FPMのログディレクトリ設定
- name: configure / Setup log directory
  file:
    path: /var/log/php-fpm
    owner: "{{ phpfpm_user }}"
    group: "{{ phpfpm_group }}"
    mode: 0755
    state: directory

##(4)PHP-FPMの起動
- name: configure / Start php-fpm service
  systemd:
    name: 'php-fpm'
    state: restarted
    enabled: yes

##(5)PHP-FMPの起動確認 
- name: configure / Wait for php-fpm restart
  wait_for:
    path: "{{ phpfpm_unix_socket }}"
    delay: 2
    timeout: 60