---
- hosts: test_servers
  tasks:
   - name: common / setup_repo / Initialized yum repository
     yum_repository:
       name: "{{ item }}"
       description: CentOS-$releasever - {{ item }}
       baseurl: http://10.44.229.62/repos/centos/$releasever/{{ item }}/$basearch/
       gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
       gpgcheck: yes
       enabled: yes
       file: CentOS-Base
     loop:
       - os
       - extras
       - updates

