---
- hosts: test_servers
  tasks:
   - name: common / setup_repo / Initialized yum repository
     yum_repository:
       name: "{{ item }}"
       description: CentOS-$releasever - {{ item }}
       baseurl: http://10.44.229.72/{{ item }}
       gpgkey: file://etc/pki/rpm-gpg/RPM-GPM-KEY-CentOS-7
       gpgcheck: yes
       enabled: yes
       file: CentOS-Base
     loop:
       - base
       - os
       - extras
       - updates