---
- name: Create Mirror Repository
  hosts: mirror_repo
  vars:
    packeges:
      - yum-utils 
      - createrepo
      - httpd
    firewalld_port:
      - 80
      - 443
    new_directory:
      - os
      - updates
      - extras
  tasks:
    - name: configure / SELinux permissive
      selinux:
        policy: targeted
        state: permissive
        when: ansible_selinux.config_mode == 'enforcing' 

    - name: check_install / Allow ports for firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop: "{{ firewalld_port }}"

    - name: Install packeges
      dnf:
        name: "{{ packeges }}"
        state: present
      become: yes
      become_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Create directories if it doesn't exist
      ansible.builtin.file:
        path: "/var/www/repos/centos/7/{{ item }}/x86_64"
        state: directory
        owner: apache
        group: apache
        mode: '0755'
      loop: "{{ new_directory }}"

    - name: rsync - os
      command: 
      rsync -avz --delete --exclude='repodata' \
      rsync://ftp.riken.jp/centos/7/os/x86_64/ \  
      /var/www/repos/centos/7/os/x86_64/
      become: yes
      become_user: root

    - name: rsync - updates
      command: 
      rsync -avz --delete --exclude='repodata' \
      rsync://ftp.riken.jp/centos/7/updates/x86_64/ \
      /var/www/repos/centos/7/updates/x86_64/
      become: yes
      become_user: root

    - name: rsync - extras
      command: 
      rsync -avz --delete --exclude='repodata' \
      rsync://ftp.riken.jp/centos/7/extras/x86_64/ \
      /var/www/repos/centos/7/extras/x86_64/
      become: yes
      become_user: root

    - name: createrepo - os
      command: createrepo /var/www/repos/centos/7/os/x86_64/
      become: yes
      become_user: root

    - name: createrepo - updates
      command: /var/www/repos/centos/7/updates/x86_64/
      become: yes
      become_user: root

    - name: createrepo - extras
      command: createrepo /var/www/repos/centos/7/extras/x86_64/
      become: yes
      become_user: root

    - name: Configure update-repo
      copy:
        src: /root/effective_ansible/sec7/update-repo
        dest: /etc/cron.daily/update-repo
        owner: root
        group: root
        mode: 0755

    - name: Configure update-repo
      copy:
        src: /root/effective_ansible/sec7/repos.conf
        dest: /etc/httpd/conf.d/repos.conf
        owner: root
        group: root
        mode: 0755

    - name: httpd restart
      systemd:
        name: httpd
        state: reloaded
        enabled: yes

    - name: Wait for httpd restart
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 80
        delay: 3
        timeout: 60