---
- name: Rolling Update for Nginx
  hosts: apps
  become: True
  serial: 1

  vars:
    cluster_service: app_cluster

##(1)更新対象のメンテナンスモードへ移行
  pre_tasks:
  - name: Disable WordPress service
    haproxy:
      state: disabled
      host: "{{ inventory_hostname }}"
      backend: "{{ cluster_service }}"
      socket: /var/run/haproxy.sock
      wait: yes
    delegate_to: "{{ item }}"
    loop: "{{ groups.lbs }}"

##(2)メインラインの最新版に設定
- name: Enable nginx-mainline YUM repository
  yum_repository:
    name: nginx-mainline
    description: NGINX Mainline Repository
    baseurl: https://nginx.org/packages/mainline/centos/7/$basearch/
    gpgcheck: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key
    enabled: yes

##(3)Nginxのアップデート作業
  roles:
   - { role: nginx, tags: nginx }

##(4)更新対象のメンテナンスモード解除
  post_tasks:
  - name: Re-enable WordPress service
    haproxy:
      state: enabled
      host: "{{ inventory_hostname }}"
      backend: "{{ cluster_service }}"
      socket: /var/run/haproxy.sock
      wait: yes
    delegate_to: "{{ item }}"
    loop: "{{ groups.lbs }}"