---
- name: Initialize OS setting for Linux Servers
  hosts: linux_server
  become: True

##プロキシ設定が必要な場合

# environment:
#   http_proxy: "http://proxy.example.local:8080"
#   https_proxy: "https://proxy.example.local:8080"

  roles:
   - role: common/locale    ##(1)ロケール管理
     tags: "locale"
   - role: common/packages  ##(2)パッケージ管理
     tags: "packages"
   - role: common/users     ##(3)ユーザー管理
     tags: "user"
   - role: common/networks  ##(4)ネットワーク管理
     tags: "net"
   - role: common/resolver  ##(5)リゾルバ管理
     tags: "resolver"

  post_tasks:
   - name: Restart target nodes
     reboot: 

   - name: Waiting connection
     wait_for_connection:
      delay: 5
      timeout: 60